# Generated by Django 4.1.8 on 2023-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name',
            field=models.CharField(default='Agence', max_length=50),
            preserve_default=False,
        ),
    ]
