# Generated by Django 4.1.8 on 2023-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_alter_agency_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionorder',
            name='trip_purpose',
            field=models.TextField(default='Placeholder'),
            preserve_default=False,
        ),
    ]
