# Generated by Django 4.1.8 on 2023-05-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_missionorder_trip_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='demand',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='action',
            field=models.CharField(default='annuler', max_length=25),
            preserve_default=False,
        ),
    ]
