# Generated by Django 4.1.8 on 2023-05-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_rename_name_transition_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.employee'),
        ),
        migrations.AlterField(
            model_name='missionorder',
            name='observation_HR',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='missionorder',
            name='observation_manager',
            field=models.TextField(),
        ),
    ]
