# Generated by Django 4.1.8 on 2023-05-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionorder',
            name='observation_HR',
        ),
        migrations.RemoveField(
            model_name='missionorder',
            name='observation_manager',
        ),
        migrations.AddField(
            model_name='missionorder',
            name='mission_summary',
            field=models.TextField(default='Rien a signaler'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ValidationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_text', models.TextField()),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.event')),
            ],
        ),
    ]
